### ISSUE TITLE
Change the version numbering

### ISSUE THREAD

**Issue by IQAndreas** [FlixelCommunity/Flixel-Power-Tools#23]
Currently, Flixel Power Tools is at **v1.9**.

Since Flixel Power Tools is so tightly linked to Flixel (especially now when we will be refactoring and moving around many of the Flixel functions), I would recommend modifying the version number of FPT so that the Flixel version it relates to is included in the version number.

A version of FPT that uses Flixel version **2.56** would have the version number `v2.56-01`. As new features are added, that increments to `v2.56-02`, then `v2.56-03` etc. 

When Flixel updates (for instance, to version **2.58**), an updated SWC of Flixel is included in the source, and a new SWC of FPT is re-compiled; the project is given the version number of `v2.58-01`.

Alternatively, the number after the `-` could stay the same rather than reset, so we get `v2.58-03` when Flixel is released, and the latter number only increments whenever there is a change to the source of Flixel Power Tools. I'm fine with either numbering system.

**Comment by Dovyski** [comment]
That's a nice idea! I like both ideas, but maybe resetting the number after the `-` every new Flixel release is easier to understand and keep track of evolution.

**Comment by IQAndreas** [comment]
Shall I complete this issue right now?

The repo is still using Flixel v2.55, so that needs to be updated anyway; I can update that SWC and set the new version number at the same time.

**Comment by Dovyski** [comment]
Yeah, you can complete this issue.

**Comment by IQAndreas** [comment]
Fixed in 5ec95b6b8e42e2bb55bdf206776caf4f57d08f3e

See also the "releases" section: https://github.com/FlixelCommunity/Flixel-Power-Tools/releases/tag/v2.56-01
